### ISSUE TITLE
AlcoR mapper 

### ISSUE THREAD

**Issue by DiegoSafian** [cobilab/alcor#1]
Hi,

I am testing AlcoR and I wanted to use the mapper. I noticed that in the example given, there is a parameter -m. Undurtunatley, I could not find it in AlcoR mapper -h. What is the function of -m?

Thanks!

**Comment by pratas** [comment]
Hi Diego,

To see what the -m stands for, please use:

AlcoR mapper  -p

This will output the information you are looking, namely 
                                                               
-m [C]:[D]:[R]:[I]:[H]:[G]/[S]:[E]:[A]                         
                                                               
Template of a target context model.                            
                                                               
Parameters:                                                    
     [C]: (integer [1;20]) order size of the regular context   
          model. Higher values use more RAM but, usually, are  
          related to a better compression score.               
     [D]: (integer [1;5000]) denominator to build alpha, which 
          is a parameter estimator. Alpha is given by 1/[D].   
          Higher values are usually used with higher [C],      
          and related to confiant bets. When [D] is one,       
          the probabilities assume a Laplacian distribution.   
     [R]: (integer [0;99999999] memory model. The 0 uses the   
          full memory.                                         
     [I]: (integer {0,1,2}) number to define if a sub-program  
          which addresses the specific properties of DNA       
          sequences (Inverted repeats) is used or not. The     
          number 2 turns ON this sub-program without the       
          regular context model (only inverted repeats). The   
          number 1 turns ON the sub-program using at the same  
          time the regular context model. The number 0 does    
          not contemple its use (Inverted repeats OFF). The    
          use of this sub-program increases the necessary time 
          to compress but it does not affect the RAM.          
     [H]: (integer [1;254]) size of the cache-hash for deeper  
          context models, namely for [C] > 14. When the        
          [C] <= 14 use, for example, 1 as a default. The      
          RAM is highly dependent of this value (higher value  
          stand for higher RAM).                               
     [G]: (real [0;1)) real number to define gamma. This value 
          represents the decayment forgetting factor of the    
          regular context model in definition.                 
     [S]: (integer [0;20]) maximum number of editions allowed  
          to use a substitutional tolerant model with the same 
          memory model of the regular context model with       
          order size equal to [C]. The value 0 stands for      
          turning the tolerant context model off. When the     
          model is on, it pauses when the number of editions   
          is higher that [C], while it is turned on when       
          a complete match of size [C] is seen again. This     
          is probabilistic-algorithmic model very usefull to   
          handle the high substitutional nature of genomic     
          sequences. When [S] > 0, the compressor used more    
          processing time, but uses the same RAM and, usually, 
          achieves a substantial higher compression ratio. The 
          impact of this model is usually only noticed for     
          [C] >= 14.                                           
     [E]: (integer [1;5000]) denominator to build alpha for    
          substitutional tolerant context model. It is         
          analogous to [D], however to be only used in the     
          probabilistic model for computing the statistics of  
          the substitutional tolerant context model.           
     [A]: (real [0;1)) real number to define gamma. This value 
          represents the decayment forgetting factor of the    
          substitutional tolerant context model in definition. 
          Its definition and use is analogus to [G].

Because this may be a lot of information there are already computed models for these parameters, which can be identified using

AlcoR mapper  -s


For your case, a simple test in DNA sequence the following parameters are valid:

AlcoR mapper --dna -v -w 5 -m 13:50:0:1:10:0.9/5:10:0.9 -k -o your_masked_sequence.fa your_sequence.fa


If your data is very large (GBs), please use

AlcoR mapper --dna -v -w 5 -m 14:50:0:1:10:0.9/5:10:0.9 -k -o your_masked_sequence.fa your_sequence.fa


Please, let us know if there are still questions.
Best regards,
